image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - formulahendry.auto-close-tag
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
    - ecmel.vscode-html-css
    - batisteo.vscode-django
